-- Gold Field Cashbox prototype schema.
-- Run this once in Supabase Dashboard -> SQL Editor before testing sync.
-- Prototype policy: anon clients can read/write all app tables.
-- Tighten this before production with real Supabase Auth and row-level project policies.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  local_user_id text unique not null,
  username text unique,
  name text not null,
  role text not null check (role in ('admin', 'manager', 'viewer')),
  pin text,
  password text,
  active integer default 1,
  created_at_local text not null,
  updated_at_local text
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  local_project_id text unique not null,
  project_name text not null,
  location text,
  active integer default 1,
  created_at_local text not null,
  updated_at_local text
);

create table if not exists public.project_users (
  id bigint generated by default as identity primary key,
  local_project_id text not null,
  local_user_id text not null,
  role_in_project text default 'manager',
  active integer default 1,
  created_at_local text not null,
  unique (local_project_id, local_user_id)
);

create table if not exists public.daily_cash (
  id bigint generated by default as identity primary key,
  local_daily_id text unique not null,
  local_project_id text not null,
  local_user_id text,
  date text not null,
  initial_usd double precision default 0,
  initial_lrd double precision default 0,
  actual_usd double precision,
  actual_lrd double precision,
  note text,
  created_by text,
  created_at_local text not null,
  updated_by text,
  updated_at_local text,
  sync_status text default 'pending'
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  local_transaction_id text unique not null,
  transaction_no text not null,
  local_project_id text not null,
  date text not null,
  type text not null check (type in ('expense', 'cash_in', 'exchange', 'transfer')),
  amount double precision not null,
  currency text not null check (currency in ('USD', 'LRD')),
  category text not null,
  note text,
  area text,
  from_currency text,
  from_amount double precision,
  to_currency text,
  to_amount double precision,
  exchange_rate double precision,
  change_usd double precision,
  change_lrd double precision,
  photo_uri text,
  transfer_to_user_id text,
  transfer_from_user_id text,
  linked_transaction_id text,
  active integer default 1,
  created_by text not null,
  created_at_local text not null,
  updated_by text,
  updated_at_local text,
  sync_status text default 'pending'
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  local_audit_id text unique not null,
  table_name text not null,
  record_id text not null,
  action text not null check (action in ('create', 'edit', 'deactivate')),
  old_value_json text,
  new_value_json text,
  edited_by text,
  edited_at_local text not null,
  local_project_id text
);

alter table public.users enable row level security;
alter table public.projects enable row level security;
alter table public.project_users enable row level security;
alter table public.daily_cash enable row level security;
alter table public.transactions enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists "prototype anon full access users" on public.users;
drop policy if exists "prototype anon full access projects" on public.projects;
drop policy if exists "prototype anon full access project_users" on public.project_users;
drop policy if exists "prototype anon full access daily_cash" on public.daily_cash;
drop policy if exists "prototype anon full access transactions" on public.transactions;
drop policy if exists "prototype anon full access audit_log" on public.audit_log;

create policy "prototype anon full access users" on public.users for all to anon using (true) with check (true);
create policy "prototype anon full access projects" on public.projects for all to anon using (true) with check (true);
create policy "prototype anon full access project_users" on public.project_users for all to anon using (true) with check (true);
create policy "prototype anon full access daily_cash" on public.daily_cash for all to anon using (true) with check (true);
create policy "prototype anon full access transactions" on public.transactions for all to anon using (true) with check (true);
create policy "prototype anon full access audit_log" on public.audit_log for all to anon using (true) with check (true);

do $$
declare
  table_name text;
begin
  foreach table_name in array array['users', 'projects', 'project_users', 'daily_cash', 'transactions', 'audit_log']
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = table_name
    ) then
      execute format('alter publication supabase_realtime add table public.%I', table_name);
    end if;
  end loop;
end $$;

insert into storage.buckets (id, name, public)
values ('transaction-photos', 'transaction-photos', false)
on conflict (id) do nothing;

drop policy if exists "prototype anon full access transaction photos" on storage.objects;
create policy "prototype anon full access transaction photos"
on storage.objects for all to anon
using (bucket_id = 'transaction-photos')
with check (bucket_id = 'transaction-photos');
